spring:
  datasource:
    url: jdbc:sqlserver://esupgradetest.southeastasia.cloudapp.azure.com:1433;databaseName=EasiShare_DB
    password: p@ssw0rd
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
        hibernate:
          default_schema: dbo
          default_catalog: EasiShare_DB
          dialect: org.hibernate.dialect.SQLServer2012Dialect
  

