spring:
  datasource:
    url: jdbc:jtds:sqlserver://192.168.31.105:1433/EasiShare_DB_T
    password: sa
    username: p@ssw0rd
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        ## SQL logging
        #        show_sql: true
        #        format_sql: false
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect